### ISSUE TITLE
Crash on SETTRGENAB

### ISSUE THREAD

**Issue by c-wilson** [billkarsh/SpikeGLX#1]
Hi Bill,

I've been using SGLX and loving it for the most part. I wanted to bring a bug in the command server to your attention. I can get everything working that I've tried except "SETTRGENAB". This command crashes spikeglx whether I pass a 0 or a 1 if acquisition is running. It does not crash if acquisition is not running, but rather returns "OK" via the socket regardless of whether I pass it a 0 or 1. If I don't pass anything (ie just send "SETTRGENAB") it will report an error in the console and return an error via the socket.

I'm running SpikeGLX v.20151231. I can try to look into the code myself to see what's going on, but I figure you might be able to solve it more efficiently than I.

Cheers

**Comment by billkarsh** [comment]
Hi Chris,

Bug confirmed…working on fix.

Bill

**Comment by billkarsh** [comment]
Fix here (version 20160101):
http://billkarsh.github.io/SpikeGLX/

**Comment by billkarsh** [comment]
Remote call to setTrgEnable routes from cmdSrv to run to graphsWindow. The latter needed to be a queued call. While retesting, noticed that setRunName would pass a _g_t decorated name to configCtl as is. Now that name is stripped. This enables graphsWindow to properly handle _g_t tags. Fixes made to current master, tagged as Release_v20160101.

**Comment by c-wilson** [comment]
So far so good for me, thanks
