### ISSUE TITLE
TTL Controlled Start and Stop - pre & post trigger times

### ISSUE THREAD

**Issue by v-hofmann** [billkarsh/SpikeGLX#11]
Hi, 

i have recorded some Neuropixel data with SpikeGLX by externally triggering the recording (i.e. latch high until trigger voltage goes back to 0). 

During data analysis I noticed there is a pre- and a post-trigger time in the recording. It seems to be 1s . Is this correct and if yes how precise is this 1s in consecutive recordings (i.e. within one run)?  I seem to have some time offset in my files (i.e. i concatinated files in for spikesorting) that i am trying to figure out and couldnt find any information regarding pre-/post trigger periods in the recordings. 

All the best
Volker

**Comment by billkarsh** [comment]
For TTL trigger, (1) Latch High mode starts recording upon TTL rising edge and stays on forever (latched) until you close gate (press Disable Recording or stop run). (2) Follow mode starts recording on TTL rising edge and stops recording on falling edge and will do this as many times as you specify. From your description, you’re running with Follow mode.

There is a box on the trigger config page to add an amount of margin. The default is 1 second. Whatever you type here is added to the recorded file just before the trigger time, and after the falling edge time in Follow mode. The time is precise. The time that was applied to your recording is noted in the metadata as item trgTTLMarginS.

A forthcoming offline helper tool (CatGT) is coming soon to help you properly sew trial files back together seamlessly and several other helpful postprocessing tasks. That is 4 to 5 weeks away.

Try to reserve the issues service of github for bug reporting and refer questions directly to me. My email can be found in the ReadMe of your download.
