### ISSUE TITLE
SMA connector as auxiliary input

### ISSUE THREAD

**Issue by Robertooooooo** [billkarsh/SpikeGLX#13]
Dear Bill,

I know that n the manual it is stated that the SMA connector on the IMEC board can be used either as a sync IN or sync OUT, stupid question: is there a way to use it as a auxiliary input too (e.g.: laser trigger from other machine)?

**Comment by billkarsh** [comment]
The manual explains this in the section header Sync/Input channels:

>>>
If an Imec BS is selected as the source, all Imec BS modules in the chassis will automatically get the signal via the chassis backplane.
For all other menu choices the imec modules are programmed to share the specified input SMA. If you are doing waveform-based sync then you MUST connect the waveform source to this input. If you have chosen Disable sync waveform then you may optionally connect any TTL signal you want to the selected SMA and that signal will be recorded as bit #6 of the SY channel in all streams. This connection can be used as a TTL trigger input if waveform sync is not being used.
The SMA connector is compatible with 0-5V TTL signals.
<<<
Please address questions about how to do things directly to me. Use the github issues tools for bug reporting. Thanks.
Bill

**Comment by Robertooooooo** [comment]
I missed that in the manual, Thanks!
