### ISSUE TITLE
Enclustra installation

### ISSUE THREAD

**Issue by shestrin** [billkarsh/SpikeGLX#15]
Device manager indicates an error with Enclustra Device. Reinstalling the Enclustra driver did not resolve the issue. Our PC is based on AMD Ryzen motherboard. Can this be an issue?

![Enclustra-issue](https://user-images.githubusercontent.com/44420378/68520828-e2dc9400-024f-11ea-9bf7-6c1b6998c54e.jpg)

**Comment by billkarsh** [comment]
So sorry, my mail system quarantined the email notification so I had no idea this issue existed until now, Mar 21, 2020!! I sure hope you could resolve this in the meantime. We have basically zero experience running anything on AMD based hardware. I'll ask Imec if they think that the enclustra drivers might be intel dependent.

**Comment by shestrin** [comment]
We installed the system in an Intel PC and it works.
Thanks,
Shaul


Shaul Hestrin, PhD

Department of Comparative Medicine

Stanford University School of Medicine

300 Pasteur Drive

Edwards Building room R314

Stanford CA 94305-5342


Tel:          (650) 498-5086


________________________________

**Comment by Haptic-Perception-Lab** [comment]
Hi Bill,
I'm having issues trying to install the Enclustra driver. It is giving me the following error: "Windows was unable to install your PCI Encryption/Decryption Controller". I downloaded the Enclustra files form your github. We have an AMD motherboard. Do you think this might be the issue?

also, when we connect the chassis to the host computer the IMEC light is blinking between red (and I think green)

**Comment by Haptic-Perception-Lab** [comment]
![error_updating_driver](https://user-images.githubusercontent.com/52719697/99306083-a52b2780-2822-11eb-85fb-586ff21030c2.png)

**Comment by billkarsh** [comment]
How enclustra behaves on AMD is outside my scope. I've written to imec requesting their comments.

**Comment by shestrin** [comment]
Thanks,
Shaul

Shaul Hestrin, PhD
Department of Comparative Medicine
Stanford University School of Medicine
300 Pasteur Drive
Edwards Building room R314
Stanford CA 94305-5342

Tel: (650) 498-5086

**Comment by Haptic-Perception-Lab** [comment]
Thanks Bill! much appreciated. Looking forward to hearing a response

**Comment by neurodroid** [comment]
We're seeing the same problem on an AMD Ryzen based system. Thanks Bill for looking into this.

**Comment by fLY9636** [comment]
Hi folks, I'm having issues with Enclustra installation on an Intel PC. 

![IMEC driver issue](https://github.com/billkarsh/SpikeGLX/assets/43393140/a674678d-41b8-4fe9-9b63-559caa16bceb)
Setup:
PC-------------12th Gen Intel(R) Core(TM) i9-12900KS, 3418 Mhz, 8 Cores
OS-------------Win10 64
RC module----ADLINK PCIe-PXIe-8683 
Chassis--------NI PXIe-1071
Enclustra issue still existed after rebooting the PC, or re-installation of cards, or switching between slots.

A view of what's in NI MAX:
![NI MAX](https://github.com/billkarsh/SpikeGLX/assets/43393140/faf155d7-41c7-417c-91b9-e7f49390212c)


Wondering if anyone who has a similar setup as listed above successfully made the system work. 
Looking forward to hearing a response! Thanks

**Comment by billkarsh** [comment]
This is the first I've heard of an issue between enclustra and intel. I've forwarded the info to imec and asked them to take it up with enclustra people.

**Comment by fLY9636** [comment]
Thank you Bill for looking into this. I also observed weird light blinking on the ADLINK PXIe board (I believe the light specifically indicates the status of the imec slot on the chassis) but not sure if that could cause any issue as with the Enclustra driver. I already emailed ADLINK and will comment here once they get back to me.

**Comment by billkarsh** [comment]
System Information Summary reported OS Version: 10.0.14393 Build 14393. This was released in 2016 so is quite old. After updating to Windows 11 the enclustra drivers installed normally.
