### ISSUE TITLE
adc bit resolution in meta file?

### ISSUE THREAD

**Issue by jaib1** [billkarsh/SpikeGLX#16]
It looks like this information is not included, would it be possible to add this?

**Comment by billkarsh** [comment]
As of NP 2.0 the metadata include item imMaxInt which, going forward, you should parse if present. If not present assume the value 512 which is correct for all probes earlier than 2.0.

**Comment by jaib1** [comment]
![image](https://user-images.githubusercontent.com/14895866/77238935-1ef40e00-6bcd-11ea-8966-40129ba44378.png)

So this table is taken from the neuropixels 1 manual. Wouldn't this mean the resolution is 1024 (2^10), or am I misunderstanding something?

**Comment by billkarsh** [comment]
2^10 = 1024 values, but they are signed, and cover range [-512, 512). The metadata item is imMaxInt which would be 512 for 10-bit signed data.
