### ISSUE TITLE
Is there any problem to turn on or off SpikeGLX after inserting Neuropixels?

### ISSUE THREAD

**Issue by geon-ung** [billkarsh/SpikeGLX#17]
When I noticed that some channels do not work while recording is already in progress, is it possible that I restart SpikeGLX after turning off the recording and changing the bank selection setting? When I realized that there is a problem with channel after inserting Neuropixels, I want to change SpikeGLX channel selection setting and insert more deeper. This Git is very helpful instruction for me. 
Thanks.

**Comment by billkarsh** [comment]
You can always stop the current run and start a new run with same or different settings at any time. You can do this with the probe inserted, which is how people do chronic recording. I hope this helps.

I'd like to reserve the GitHub issues area for software bug reports. How-To questions like this are better handled as a direct question to me <karshb@hhmi.org> or even better, in the user community discussion forum here <https://join.slack.com/t/neuropixelsgroup/shared_invite/enQtMzExMzEyMjg1MDE1LTg4NzJjZjIxNjA0M2YxNzBiNWRjOTc5MzMwZjgyMDk1ZmJiYzMxNTQyZGYwZmZlYjk1ODcwMTRmNWJiZGI3YjE>.
-- Bill
