### ISSUE TITLE
Run with sync

### ISSUE THREAD

**Issue by lihao881230** [billkarsh/SpikeGLX#19]
Hi Bill,

This is an amateur question, but I am trying to run the sync waveform with the latest release (20200520), and it always gives me errors saying " sync pulser not detected". I tried using both NI and Imec as the source, and both of them were successfully generating the sync waveform when I measured it by an oscilloscope. However, it gave the same errors each time. I was wondering if I didn't correctly connect the wires.

We have NI-6166 and BNC-2110. When I chose NI as the source, I had a single SMA cable connecting the SMA connector on the Imec and PFI-13/P2.5 on the BNC-2110. When I chose Imec as the source, I had either a single SMA cable connecting to any of the PFI slots on the BNC-2110 or an SMA cable connecting to a BNC adaptor which splits into 2 wires that connected to any of the PFI slots and to digital ground. 

Thank you in advance,

Hao

**Comment by billkarsh** [comment]
This was resolved on the Slack channel. User needed to send sync signal to one of the recorded NI channels via a real wire.
