### ISSUE TITLE
Specify probe for CatGT in runit.bat

### ISSUE THREAD

**Issue by Idavr** [billkarsh/SpikeGLX#20]
Hi there!

I've downloaded and started trying to run CatGT for artifact removal on my Neuropixel data acquired with SpikeGLX (following instructions here: http://billkarsh.github.io/SpikeGLX/), but I am having some trouble with defining the right argument for "prb" in the runit.bat file. I've re-read the readme-file and tried other sites for information of how to specify that the probe I am using is the phase3B with a checkered pattern. In the readme.txt there were good examples and explanations for most of the arguments, but only phase3A was mentioned for the argument specifying the probe. I initially assumed there wouldn't be much of a difference, but when running the cleaned data through kilosort2 and then also looking at the probe view in phy2, there were imaged four probes instead of just one. This was not found when running the raw (not-CatGT) data through the same pipeline, which is why I am thinking the specification of the probe might be the reason. 

How should you define the "prb" argument in runit.bat to indicate a phase3B probe was used?

**Comment by billkarsh** [comment]
Use CatGT parameter -prb_3A if and only if your experiment was done with 3A probes. The 3A software can run only one probe at a time and names binary and meta files with tag .imec. having no probe index number in it. All PXI versions of SpikeGLX can run multiple probes. The probes and their output files get a zero-based logical index number; e.g. .imec0. tag in the name. Run CatGT on these probes by listing their indices in a list like this -prb=0, or, -prb=1,3:7. I've asked Jennifer Colonell to follow up about the problems you are having with phy.

I'd like to reserve the GitHub issues area for SpikeGLX-specific bug reports. How-To questions like this are better handled as a direct question to me karshb@hhmi.org or even better, in the user community discussion forum here https://join.slack.com/t/neuropixelsgroup/shared_invite/enQtMzExMzEyMjg1MDE1LTg4NzJjZjIxNjA0M2YxNzBiNWRjOTc5MzMwZjgyMDk1ZmJiYzMxNTQyZGYwZmZlYjk1ODcwMTRmNWJiZGI3YjE.
-- Bill
