### ISSUE TITLE
NP1.0 vs NP2.0

### ISSUE THREAD

**Issue by bfpcruz** [billkarsh/SpikeGLX#23]
Hi,

We are about to try out the new 2.0s, but after reading the README I am a bit confused about some of the points:

1)
`- As always, you should calibrate your HS sample clock rates. These are stored in SpikeGLX using the HS serial number as the key because this a measurement about that particular part. However, imec did not include an EEPROM chip on the 2.0 HS so the HS does not know its own serial number. SpikeGLX will require you to type the serial number into a dialog when you click Detect. You need to have read that from the label on the HS. This will be corrected for 2.0 headstages by imec later.`
However, using the latest spikeglx version it seems the HS serial number is getting detected automatically (under HSSN). Am I missing something? 

2) 
`- Previously we had said it was alright to run NP 20 and NP 1.0 copies of SpikeGLX concurrently. However, we know that 1.0 interferes with data from 2.0 when runs are stopped or started and we don't know if there is interference at other times, so we advise against this now.
`
Can you confirm if this is still the case and, if so, what do you advise to do (i.e. restarting the software each time we switch probes or just have 2 simultaneous versions running on the same computer).

3)
RE channelmaps. Am I correct to assume that NPtype21_bank0_refX.imro are the maps that correspond to the deepest channels of the probe in the densest configuration (similar to the NP1.0 default)?

Thanks!
B

**Comment by billkarsh** [comment]
Hi,

Please see the download page for the software https://billkarsh.github.io/SpikeGLX/.

- It explains you should not use anything other than SpikeGLX 3.0. The latest software runs both 2.0 and 1.0 hardware at the same time. That answers issue 2.

- The ‘Problems?’ section of the download page explains that you should contact the slack channel or me (email) for user questions but not use the github issues list. I’ll delete your issue when your questions are answered.

Issue 1) NP 2.0 headstages do not have an EEPROM. You need to do what the instructions say for 2.0 HS calibration. Raed the serial number from the part and enter it manually.

Issue 3) Bank 0 is always the tip (deepest) for all probe types.

Bill
