### ISSUE TITLE
Different recording lengths for files acquired simultaneously?

### ISSUE THREAD

**Issue by m-beau** [billkarsh/SpikeGLX#24]
Hi,

I am trying to understand whether it is necessary to re-align two files acquired simultaneously with spikeGLX through 2 Neuropixels probes plugged into the same NI card.

As the acquisition of the two files is started and stopped simultaneously using the GUI, I presumed that the two recordings should have the exact same size. What a surprise it was to find out that the metafiles `fileSizeBytes` and `fileTimeSecs` variables were actually different! They differ from several tens of milliseconds in all my recordings, in a variable manner (around 20ms).

If I understand it properly, the variable `firstSample` corresponds to the index of the first sample of the acquisition (which is simply displayed on the screen) being actually saved on disk. This variable is matches on both meta files - I assume that it means that the two recordings were started simultaneously, but not stopped simultaneously. Does it mean that it is indeed correct to directly compare the times of spikes found on the two recordings without having to re-align them (with the sync channel)?

Thanks a lot.

**Comment by m-beau** [comment]
Update: I just checked and there seems to be a continuous drift between the sync channels of 2 files recorded on the same card - they start with a difference of 85ms and end with a difference of 280ms after about 1h40 of recording. I would still be interested in understanding why such a drift occurs, given that they are referenced to the same CPU clock!

**Comment by billkarsh** [comment]
Please use my email to tell me about questions that are not bugs. Use github issues for bugs.

The probes run asynchronously via clocks in the headstages. The start signal is issued in common. The lengths of the files are not controlled except in trigger modes that specify a desired length.

You need to align two different probes, with the exception of two 2.0 probes in the same headstage.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by m-beau** [comment]
Hi,

Sorry for posting this here - I will use your email in the future.

Thank you for your answer, got it!
Best
