### ISSUE TITLE
First run

### ISSUE THREAD

**Issue by bladedcharleco** [billkarsh/SpikeGLX#25]
Hi, I wanted to make a first run to test if everything is working fine with a neuropixel dummy probe, but it keeps giving the error 33. This makes me wonder if its possible or not for SpikeGLX to recognize the probe even if there are no calibration files as it is the case with the dummy probes. Thanks.

**Comment by billkarsh** [comment]
Please use my email to tell me about questions that are not bugs. Use github issues for bugs.

1. A dummy probe does not function electrically. You can't talk to it with SpikeGLX.
2. Generally, calibration files improve accuracy but are not required, especially not for your basic procedure testing.
3. Try connecting to your real probe while it rests in its foam box. It helps to remove the foam insert from the cardboard.
4. Error 33, (bad port number) likely means your firmware is not installed correctly. Please read the help in the Update Firmware dialog and follow those instructions carefully. I believe if your firmware is malfunctioning the enclustra drivers will NOT show up in the device manager. Also, you will not get a green LED on the module.

Please resume further discussion using email to me as instructed here: https://billkarsh.github.io/SpikeGLX/#questions-or-problems
