### ISSUE TITLE
SpikeGLX_v20230101 is missing NeuropixAPI_x64_3_57.dll

### ISSUE THREAD

**Issue by bramn22** [billkarsh/SpikeGLX#27]
Hi,

When starting the new spikeglx version 20230101-phase30, I'm getting an error that NeuropixAPI_x64_3_57.dll is missing. In the spikeglx folder, it contains a NeuropixAPI_x64_3_52.dll but no ..._3_57.dll. Could it be that the wrong file was included in this release?

Best,
Bram

**Comment by billkarsh** [comment]
Oops. The download will be replaced by 8am PST.

**Comment by bramn22** [comment]
Thanks!
