### ISSUE TITLE
SpikeGLX error 8

### ISSUE THREAD

**Issue by YgGao111** [billkarsh/SpikeGLX#28]

**Comment by billkarsh** [comment]
Error 8 is a probe Timeout error. The probe isn't responding to initial handshaking in time. This is usually a fatal communications error, that is, the probe is damaged. The preferred way of getting help is described here:
https://billkarsh.github.io/SpikeGLX/#questions-or-problems

**Comment by Yinggang2023** [comment]
> Error 8 is a probe Timeout error. The probe isn't responding to initial handshaking in time. This is usually a fatal communications error, that is, the probe is damaged. The preferred way of getting help is described here: https://billkarsh.github.io/SpikeGLX/#questions-or-problems.

Thanks for your help. The problem had been solved.

**Comment by billkarsh** [comment]
If you don't mind, how was it solved, since this is basically a dead probe.

**Comment by Yinggang2023** [comment]
I got this error simply because the loose connection between the probe and the headstage.
