### ISSUE TITLE
SpikeGLX not saving configuration

### ISSUE THREAD

**Issue by miou** [billkarsh/SpikeGLX#31]
Dear Bill,

I noticed that since the newest version of SpikeGLX, configurations don't seem to be saved. So, each time I run a new acquisition, I have to re-do all the probe config, NI setup etc. Pressing save seems to have no effect. Also, once the GUI showing the traces opens, the Yscl etc parameters are not saved from the previous recording, as used to be the case and helpful in previous versions.

--Janis

**Comment by billkarsh** [comment]
Hi Janis, We can't confirm this, and other users would surely have complained about it...so there is an issue on your computer. All the settings are saved to folder _Configs in the same folder as SpikeGLX.exe. The folder is automatically generated if not present. Do you see that folder? Do you see files of type *.ini within it? My only guess is that you are running as a user who does not have permissions to write to that folder. Right-click on _Configs or the parent SpikeGLX folder and select Properties/Security to see the permissions. Let me know.

**Comment by miou** [comment]
Ah, yes, the problem was on my side. Thank you so much, that fixed it!
