### ISSUE TITLE
live time precision

### ISSUE THREAD

**Issue by xingberlin** [billkarsh/SpikeGLX#32]
Hi, when recording with SpikeGLX, recording time was updated lively at second level in the up right corner, such as '<G0T0> 00:12:32'. Is it possible to have it shown more precisely, for example, at ms level?

**Comment by billkarsh** [comment]
I wouldn't change that elapsed time display to ms for two main reasons. The most important is the update event traffic would be very high and it would degrade the responsiveness of the GUI. Secondly, if it updated realistically it would be too fast to convey any information to a human.
