### ISSUE TITLE
Dock ID out of range

### ISSUE THREAD

**Issue by cguerreromar** [billkarsh/SpikeGLX#35]
Hello bilkarsh,
I was trying to callibrate a new Neuropixel 2.0 probe on SpikeGLX. Every time I want to detect the probe to do so I get a message saying 'Dock ID out of range: 1>0' . Given that on each slot each port contains two docks, I was wondering where might the dock number assignation come from and if there's a way to reconfigure it. I tried to update the firmware but I still face the same problem. The headstage seems to be correctly connected to the probe and to the acquisition box. Here I attach a screenshot of what I see. Thanks a lot in advance for the help!

![image](https://github.com/billkarsh/SpikeGLX/assets/99739721/04791608-160d-49f1-a615-ad6c17bb5a4a)

**Comment by billkarsh** [comment]
Your current SpikeGLX version is 20201103. Please get the latest version and update to the firmware that is included in that download.
