### ISSUE TITLE
IMEC readElectrodeData(slot 2, port 4, dock1)error 30'FpgaManager lO error: Blocking memory mapped transfer did not complete

### ISSUE THREAD

**Issue by DaohanZhang** [billkarsh/SpikeGLX#36]
Hello！My recording in spikeGLX repeatedly stopped approximately 20min with the following issue. But the recording will be saved. Did anybody face similar problem during recording over several minutes using SpikeGLX? What could the error be?
![111111](https://github.com/user-attachments/assets/75f32fee-4629-4b75-a37b-5f7e43661943)

**Comment by DaohanZhang** [comment]
I also pinned some details in the reply of the slack: https://neuropixelsgroup.slack.com/archives/C93JDLKJP/p1729169323704799

**Comment by billkarsh** [comment]
This is a loose connection, either between basestation and probe, or between PC and chassis.
