### ISSUE TITLE
Include gate and trigger number in the metadata

### ISSUE THREAD

**Issue by h-mayorquin** [billkarsh/SpikeGLX#38]
Hi,

Looking at many examples and the metadata guide here:
https://github.com/billkarsh/SpikeGLX/blob/master/Markdown/Metadata_30.md

It seems that there is no way of determining the gate and trigger number from a .meta file. The only place where this seems recorded is on the file path which is brittle because many users decide to change this.  Given this, I think it would be a good idea to store the gate and trigger number somewhere on the metadata to improve data provenance.

Could this be done? is this a bad idea or are there any complications that I am failing to see?

**Comment by billkarsh** [comment]
No. The binary and meta files need to be associated. Only possible through the file name. This has survived 12 years of use. Users should not arbitrarily rename things. Sorry.

**Comment by h-mayorquin** [comment]
Thanks,

To be clear, we are not recommending users to change the names of their files or changing the filenames ourselves.[ We are a library that transforms native formats to NWB](https://github.com/catalystneuro/neuroconv) and we have encountered users who modify their filenames (the file name does not match with the `fileName` in the meta)  more than once. We were thinking that a designated field on the ini-like .meta files for this information could make the format more robust and streamlined for readers and consumers of the .meta files.

That said, I understand that you would not like to incentivise what you feel is a bad practice by facilitating this. 

Quick question: is there a way in which the the gate and trigger information is omitted from the filename? We got data with the following meta:

```
acqApLfSy=384,0,1
appVersion=20201012
fileCreateTime=2021-07-02T14:43:02
fileName=D:/SGL_DATA/2021-07-02_14-42-31/npx.imec1.ap.bin
```

As you can see the `fileName` does not  have the gate and trigger information as usual Is this the result of `CatGT`?

**Comment by billkarsh** [comment]
CatGT observes and preserves the file name conventions because they are essential. This file has a rather atypical naming scheme that is not representative. Where did you get it?

Can we continue this conversation in a slack DM, because it is not a bug. Thanks.
