### ISSUE TITLE
MATLAB SDK StartRun crashes SpikeGLX

### ISSUE THREAD

**Issue by brykko** [billkarsh/SpikeGLX#4]
Hi Bill,

I have successfully performed a number of operations using the MATLAB API, but when I try using the `StartRun` command, this causes SpikeGLX to crash every time (the generic "SpikeGLX has stopped working" dialog appears). If I start SpikeGLX running manually, then I can use `StopRun` without any problems. I'm working with MATLAB R2017a and SpikeGLX v20171101-phase3A. Might I be using the API commands incorrectly, or is this a bug?

Thanks,
Rich

**Comment by billkarsh** [comment]
Hi Rich,

I confirm your bug with MATLAB API StartRun. The fix will be included in the next release (a few days hence).

The next release will include several improvements to the graph filters, which are inspired by the slow graph performance of BinMax you reported.

I am closing this issue. Thanks for improving SpikeGLX.
Bill

**Comment by brykko** [comment]
Great to hear there will be a fix soon, that will be really useful.

I've noticed a couple more (less critical) problems with the MATLAB SDK, which I'll raise in separate issues.

**Comment by billkarsh** [comment]
Hi Rich,

You can list the problems en masse. Sooner is better.
Thanks,
Bill
________________________________________

**Comment by brykko** [comment]
OK sure – 

1) MATLAB SpikeGL objects appear to expire after a few seconds. I guess there's no problem with that per se, but if I attempt to call a method of an expired SpikeGL object, this causes MATLAB to hang indefinitely.

2) The "GetRunName" method throws an error, apparently because of an incorrect field name in the MATLAB code.

**Comment by billkarsh** [comment]
Hi Rich,

Good detective work. I confirm both of these problems. The fixes will be rolled into the next release.

On the MATLAB client side, stale handles will now automatically reconnect if the socket has timed out. The only penalty is that a warning message is sent to the Command Window if that happened, but it does not interrupt a running script. You can set a longer timeout in the SpikeGLX Command Server Dialog if that behavior is problematic.

I will close these issues.

**Comment by billkarsh** [comment]
Fixed. Closing issue.
