### ISSUE TITLE
AMD - CPUs

### ISSUE THREAD

**Issue by arturoptophys** [billkarsh/SpikeGLX#5]
Hello,
I have a question regarding the System Requirements for PXI.
Are there any Intel optimized Libraries in use in SpikeGLX, which would speak against the use of an AMD CPU (e.g.  Threadripper 1920X ) for computersystem interfacing PXIe-based Neuropixels setup?

Best,
Artur

**Comment by billkarsh** [comment]
Hi Artur,

There is no programming in SpikeGLX that assumes a particular CPU or instruction set is present. We have some experience on different Intel CPUs, so there is at least some degree of CPU independence. AMD needs to compete with Intel so they would have made sure they can run important apps like Office and Photoshop. I expect more similarity than difference. However, we have no experience on AMD at all. I can’t guarantee that there won’t be some differences.

Bill
