### ISSUE TITLE
NI sync signal PFI-13 on Phase3A

### ISSUE THREAD

**Issue by babaq** [billkarsh/SpikeGLX#7]
Hi Bill,

I am trying to sync the imec and NI in a 3A system, the manual says the SpikeGLX can program NI to generate 1Hz 50% duty cycle Sync signal on `PFI-13`. we have a `Whisper` breakout panel connected to NI USB-6366 which count channels from 0-231. 

Which channel is this PFI-13, how can I get the signal and feeds to the sync channels of imec and NI.

Best,

Alex

**Comment by billkarsh** [comment]
Hi Alex,

We need to mail you out a breakout dongle. Reply directly to me with mailing info. Don’t do this in a github issue.

karshb@janelia.hhmi.org<mailto:karshb@janelia.hhmi.org>
Bill

**Comment by billkarsh** [comment]
Breakout connector just shipped, allow ~5 days.

**Comment by babaq** [comment]
@billkarsh Thank you.
