### ISSUE TITLE
default channel map seems outdated

### ISSUE THREAD

**Issue by agbondy** [billkarsh/SpikeGLX#8]
The default channel map is 2-column but with Neuropixels 1.0 (and even most recent 3b testing probes) shouldn't the default now be staggered, 4 column?

**Comment by billkarsh** [comment]
The probes are all two columns, but on some the rows are displaced a little left and right. Our shank map is only intended to give a rough idea of where you are on the probe. This is not affecting the accuracy of data recording.
Bill

________________________________

**Comment by agbondy** [comment]
I see, OK.
