### ISSUE TITLE
format of nidq binary file

### ISSUE THREAD

**Issue by agbondy** [billkarsh/SpikeGLX#9]
Hi again Bill! A question about parsing the nidq binary files. We are recording with 3b probes and NI acquisition system here in the Brody lab. For my recent recordings, I acquired two digital channels on the nidq stream (one for syncing with imec and and the other for syncing with the animal's behavior) but I seem to only have one channel of data in the *.nidq.bin file that has somehow multiplexed both inputs. (As far as I can tell, unique values in the binary data are 0, 1, 2 and 3, where and 1 and 2 mean just channel 1 or just channel 2 high respectively and 3 means both high). Perhaps I'm just interpreting this wrong? Can you clarify the format of multi-channel nidq binary files?  Thanks!

**Comment by billkarsh** [comment]
Hi Adrian,

Please use the github to report confirmed bugs. If you have a suspected bug or just need help please write to me directly.

NI binary channels are packed together, up to 16 at a time, into 16-bit output channels. This is documented in the user manual. If the manual does not answer your question, let me know.
Bill

**Comment by agbondy** [comment]
Got it. I figured out the file format and will contact you directly if I have questions going forward. Thanks!

**Comment by Qifan94** [comment]
> Got it. I figured out the file format and will contact you directly if I have questions going forward. Thanks!

Hi, Adrian. May I have your email please? I also have some problem when I am tring to record behaviour marker from NI device.
